[package]
authors = ["Frequency"]
description = "FRAME pallet to manage treasury"
edition = "2021"
homepage = "https://substrate.io"
license = "Apache-2.0"
name = "pallet-treasury"
publish = false
repository = "https://github.com/frequency-chain/frequency/"
version = "27.0.0"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive", "max-encoded-len"] }
docify = { workspace = true }
impl-trait-for-tuples = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
serde = { features = ["derive"], optional = true, workspace = true, default-features = true }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
pallet-balances = { workspace = true, default-features = false }
sp-runtime = { workspace = true }
sp-core = { workspace = true, optional = true }

# Frequency related dependencies
common-primitives = { default-features = false, path = "../../common/primitives" }

[dev-dependencies]
sp-io = { workspace = true }
pallet-utility = { workspace = true }
common-runtime = { path = "../../runtime/common", default-features = false }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-utility/std",
	"scale-info/std",
	"serde",
	"sp-core?/std",
	"sp-io/std",
	"sp-runtime/std",
	"common-primitives/std",
	"common-runtime/std",
]
runtime-benchmarks = [
	"dep:sp-core",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"common-primitives/runtime-benchmarks",
	"common-runtime/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-utility/try-runtime",
	"sp-runtime/try-runtime",
]
test = []

[lints]
workspace = true
