[package]
name = "paseo-emulated-chain"
version = "0.0.0"
authors = ["Frequency"]
edition = '2021'
description = "Paseo emulated chain used for integration tests"
publish = false

[dependencies]

# Substrate
# sp-core = { workspace = true, default-features = true }
sp-core = { version = "35.0.0", default-features = true }
sp-runtime = { version = "40.1.0", default-features = true }
# sp-runtime = { workspace = true, default-features = true }
# authority-discovery-primitives = { workspace = true, default-features = true }
# babe-primitives = { workspace = true, default-features = true }
# beefy-primitives = { workspace = true, default-features = true }
# grandpa = { workspace = true }
# pallet-staking = { workspace = true, default-features = true }

# Polkadot
# polkadot-primitives = { workspace = true, default-features = true }
polkadot-primitives = { version = "17.1.0", default-features = true}

# Cumulus
# parachains-common = { workspace = true, default-features = true }
parachains-common = { version = "19.0.0", default-features = true }
# emulated-integration-tests-common = { workspace = true }
emulated-integration-tests-common = { version = "19.0.2" }

# Runtimes
# paseo-runtime-constants = { workspace = true, default-features = true }
# paseo-runtime = { workspace = true }

authority-discovery-primitives = { version = "35.0.0", default-features = true, package = "sp-authority-discovery" }
babe-primitives = { version = "0.41.0", default-features = true, package = "sp-consensus-babe" }
beefy-primitives = { version = "24.1.0", default-features = true, package = "sp-consensus-beefy" }
grandpa = { version = "0.33.0", package = "sc-consensus-grandpa" }
pallet-staking = { version = "39.1.0", default-features = true}

# paseo-runtime-common = { version = "19.1.0", default-features = false }
paseo-runtime = { git = "https://github.com/paseo-network/runtimes", package = "paseo-runtime", tag = "1.5.1-relay", default-features = true}
paseo-runtime-constants = { git = "https://github.com/paseo-network/runtimes", tag = "1.5.1-relay", package = "paseo-runtime-constants", default-features = true }


[features]
runtime-benchmarks = [
	"pallet-staking/runtime-benchmarks",
	"parachains-common/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"paseo-runtime-constants/runtime-benchmarks",
	"paseo-runtime/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]