[package]
authors = ["Frequency"]
edition = '2021'
homepage = "https://frequency.xyz"
license = "Apache-2.0"
name = 'frequency-paseo-emulated-chain'
publish = false
version = "0.0.0"

[dependencies]
xcm-emulator = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
parachains-common = { workspace = true }
polkadot-primitives = { workspace = true }

emulated-integration-tests-common = { workspace = true }
frequency-runtime = { path = "../../../runtime/frequency", features = [
  "frequency-testnet",
  "frequency-bridging",
  "frequency-lint-check",
] }

cumulus-primitives-core = { workspace = true }
sp-keyring = { workspace = true }
frame-support = { workspace = true }
staging-xcm = { workspace = true }
