[package]
authors = ["Frequency"]
name = "paseo-emulated-chain"
edition = '2021'
license = "Apache-2.0"
description = "Paseo emulated chain used for integration tests"
publish = false

[dependencies]

# Substrate
# sp-core = { workspace = true, default-features = true }
sp-core = { version = "35.0.0", default-features = true }
# sp-runtime = { workspace = true, default-features = true }
sp-runtime = { version = "40.1.0", default-features = true }
authority-discovery-primitives = { version = "35.0.0", default-features = true, package = "sp-authority-discovery" }
# authority-discovery-primitives = { workspace = true, default-features = true }

babe-primitives = { version = "0.41.0", default-features = true, package = "sp-consensus-babe" }
# babe-primitives = { workspace = true, default-features = true }

beefy-primitives = { version = "23.0.0", default-features = true, package = "sp-consensus-beefy" }
# beefy-primitives = { workspace = true, default-features = true }

grandpa = { version = "0.33.0", package = "sc-consensus-grandpa", default-features = true }
# grandpa = { workspace = true, default-features = true }

pallet-staking = { version = "39.1.0", default-features = true }
# pallet-staking = { workspace = true, default-features = true }

# Polkadot
polkadot-primitives = { version = "17.1.0", default-features = true }
# polkadot-primitives = { workspace = true, default-features = true }

# Cumulus
parachains-common = { version = "19.0.0", default-features = true }

# parachains-common = { workspace = true, default-features = true }

# emulated-integration-tests-common = { version = "19.0.2" }
emulated-integration-tests-common = { version = "19.0.2" }
# emulated-integration-tests-common = { workspace = true }
# emulated-integration-tests-common = { workspace = true }

# Runtimes
paseo-runtime-constants = { package = "paseo-runtime-constants", git = "https://github.com/paseo-network/runtimes", tag = "1.5.1-relay", default-features = true }
# paseo-runtime-constants = { package = "paseo-runtime-constants", path = "relay/paseo/constants", default-features = true }
# paseo-runtime-constants = { workspace = true, default-features = true }


paseo-runtime = { package = "paseo-runtime", git = "https://github.com/paseo-network/runtimes", tag = "1.5.1-relay", default-features = true }
# paseo-runtime = { workspace = true, default-features = true }

# [features]
# runtime-benchmarks = [
# 	"pallet-staking/runtime-benchmarks",
# 	"parachains-common/runtime-benchmarks",
# 	"polkadot-primitives/runtime-benchmarks",
# 	"paseo-runtime-constants/runtime-benchmarks",
# 	"paseo-runtime/runtime-benchmarks",
# 	"sp-runtime/runtime-benchmarks",
# ]