name: Reset Self-hosted Runner
description: Shared action that allows to reset a runner to its original state
runs:
  using: "composite"
  steps:
    - name: Remove /home/runner
      shell: bash
      run: |
        whoami
        echo "***> BEFORE removal of /home/runner dir:"
        ls -la /home
        echo "Removing no longer used /home/runner dir..."
        rm -fr /home/runner
        echo "***> After removal of /home/runner dir:"
        ls -la /home
    - name: Remove Cargo Generated Artifacts
      shell: bash
      run: |
        echo "Removing generated cargo artifacts..."
        rm -fr ./target
        rm -rf ./runtime/frequency/target
    - name: Remove NPM node Modules
      shell: bash
      run: |
        find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +
    - name: Prune Docker Resources
      shell: bash
      run: |
        set -x
        if [ "$(which docker)" ] && [ "$(docker --version)" ]; then
          echo "Docker is found. Cleaning..."
          containers=$(docker ps --all --quiet)
          if [ ! -z "$containers" ]; then
            docker container rm -f $containers;
          fi
          docker container ls -a
          docker system prune -a --volumes
          docker image prune -a -f --filter "until=720h"
          echo "Finished cleaning docker resources."
        else
          echo "Docker's not found. Exiting..."
          exit 0
        fi
