[package]
name = "pallet-frequency-tx-payment-rpc"
version = "0.0.0"
description = "A package that adds RPC to payment pallet"
authors = ["Frequency"]
license = "Apache-2.0"
publish = false
homepage = "https://frequency.xyz"
repository = "https://github.com/frequency-chain/frequency/"
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true }
jsonrpsee = { workspace = true, features = ["client-core", "server", "macros"] }
rayon = { workspace = true }
# Frequency crates
pallet-frequency-tx-payment-runtime-api = { default-features = false, path = "../runtime-api" }
common-primitives = { default-features = false, path = "../../../../common/primitives" }
common-helpers = { default-features = false, path = "../../../../common/helpers" }
# Substrate crates
sp-core = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-runtime = { workspace = true }
sp-rpc = { workspace = true }
sp-weights = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "time", "parking_lot"] }
sc-client-api = { workspace = true }

[features]
default = ["std"]
std = [
  "sp-core/std",
  "parity-scale-codec/std",
  "sp-api/std",
  "sp-runtime/std",
  "pallet-frequency-tx-payment-runtime-api/std",
  "common-primitives/std",
  "common-helpers/std",
]
