import { SchemaInfo } from './schemas';

export const SCHEMA_INFOS: SchemaInfo[] = [
  {
    id: 11,
    namespace: 'dsnp',
    name: 'user-attribute-set',
    version: 1,
    deprecated: true,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 20,
    namespace: 'dsnp',
    name: 'user-attribute-set',
    version: 2,
    deprecated: false,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 15,
    namespace: 'dsnp',
    name: 'profile-resources',
    version: 1,
    deprecated: false,
    modelType: 'AvroBinary',
    payloadLocation: 'Itemized',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 7,
    namespace: 'dsnp',
    name: 'public-key-key-agreement',
    version: 1,
    deprecated: false,
    modelType: 'AvroBinary',
    payloadLocation: 'Itemized',
    appendOnly: true,
    signatureRequired: true,
  },
  {
    id: 4,
    namespace: 'dsnp',
    name: 'reaction',
    version: 1,
    deprecated: false,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 5,
    namespace: 'dsnp',
    name: 'update',
    version: 1,
    deprecated: true,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 19,
    namespace: 'dsnp',
    name: 'update',
    version: 2,
    deprecated: false,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 8,
    namespace: 'dsnp',
    name: 'public-follows',
    version: 1,
    deprecated: false,
    modelType: 'AvroBinary',
    payloadLocation: 'Paginated',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 10,
    namespace: 'dsnp',
    name: 'private-connections',
    version: 1,
    deprecated: false,
    modelType: 'AvroBinary',
    payloadLocation: 'Paginated',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 13,
    namespace: 'dsnp',
    name: 'ext-content-attribute-set',
    version: 1,
    deprecated: false,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 6,
    namespace: 'dsnp',
    name: 'profile',
    version: 1,
    deprecated: false,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 3,
    namespace: 'dsnp',
    name: 'reply',
    version: 1,
    deprecated: true,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 18,
    namespace: 'dsnp',
    name: 'reply',
    version: 2,
    deprecated: false,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 1,
    namespace: 'dsnp',
    name: 'tombstone',
    version: 1,
    deprecated: true,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 16,
    namespace: 'dsnp',
    name: 'tombstone',
    version: 2,
    deprecated: false,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 9,
    namespace: 'dsnp',
    name: 'private-follows',
    version: 1,
    deprecated: false,
    modelType: 'AvroBinary',
    payloadLocation: 'Paginated',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 14,
    namespace: 'dsnp',
    name: 'public-key-assertion-method',
    version: 1,
    deprecated: false,
    modelType: 'AvroBinary',
    payloadLocation: 'Itemized',
    appendOnly: false,
    signatureRequired: true,
  },
  {
    id: 2,
    namespace: 'dsnp',
    name: 'broadcast',
    version: 1,
    deprecated: true,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 17,
    namespace: 'dsnp',
    name: 'broadcast',
    version: 2,
    deprecated: false,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
  {
    id: 12,
    namespace: 'dsnp',
    name: 'dsnp-content-attribute-set',
    version: 1,
    deprecated: false,
    modelType: 'Parquet',
    payloadLocation: 'IPFS',
    appendOnly: false,
    signatureRequired: false,
  },
];
