# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build Westend
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  push:

env:
  NIGHTLY_TOOLCHAIN: nightly-2025-04-03

jobs:
  release-node-images:
    name: Release ${{matrix.arch}} Node Docker Image for ${{matrix.network}}
    strategy:
      fail-fast: true
      matrix:
        arch: [amd64]
        network: [testnet-westend]
        build-profile: [release]
        docker-platform: [linux/amd64]
        release-file-name-prefix: [frequency-testnet-westend]
    env:
      DOCKER_HUB_PROFILE: frequencychain
      IMAGE_NAME: parachain-node
      NEW_RELEASE_TAG: v0.0.2
    runs-on: ubuntu-24.04
    steps:
      - name: Set Env Vars
        run: |
          echo "BIN_DIR=target/${{matrix.build-profile}}" >> $GITHUB_ENV
          echo "BUILT_BIN_FILENAME=frequency" >> $GITHUB_ENV
          echo "RELEASE_BIN_FILENAME=${{matrix.release-file-name-prefix}}.${{matrix.arch}}" >> $GITHUB_ENV
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Move Binary to Target Dir
        run: |
          mkdir -p ${{env.BIN_DIR}}
          mv ./frequency ${{env.BIN_DIR}}/${{env.BUILT_BIN_FILENAME}}
          chmod +x ${{env.BIN_DIR}}/${{env.BUILT_BIN_FILENAME}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{matrix.arch}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and Push Parachain Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{matrix.docker-platform}}
          push: true
          file: ./docker/${{env.IMAGE_NAME}}.dockerfile
          tags: |
            ${{env.DOCKER_HUB_PROFILE}}/${{env.IMAGE_NAME}}-${{matrix.network}}:${{env.NEW_RELEASE_TAG}}
